version: 2.1
executors:
  docker-executor:
    docker:
      - image: circleci/python:3.9

jobs:
  build_and_push_image:
    executor: docker-executor
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io

      - run:
          name: Build Docker image
          command: docker build -t yakengne/python_api:1.0 .

      - run:
          name: Log in to Docker Hub
          command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

      - run:
          name: Push Docker image to Docker Hub
          command: docker push yakengne/python_api:1.0

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_and_push_image



