version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202106-01
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.8

      # Your existing steps for building and pushing the Docker image
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t yakengne/python_api.1.0 .
            docker login -u yakengne -p $DOCKERHUB_PASSWORD
            docker push yakengne/python_api.1.0
