version: 2.1
jobs:
  build:
    docker:
      - image: docker:stable-git  # Use the docker:dind service image
    steps:
      - checkout

      # Build the Docker image
      - run:
          name: Build Docker image
          command: |
            docker build -t yakengne/python_api:1.0 .

      # Log in to Docker Hub
      - run:
          name: Log in to Docker Hub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      # Push the Docker image to Docker Hub
      - run:
          name: Push Docker image to Docker Hub
          command: docker push yakengne/python_api:1.0

workflows:
  version: 2
  build_and_push:
    jobs:
      - build




