version: 2.1
executors:
  docker-executor:
    docker:
      - image: circleci/python:3.9

jobs:
  build:
    executor: docker-executor

    steps:
      - checkout
      - run:
          name: Set ulimit value
          command: ulimit -n 4096
      - run:
          name: Install Docker
          command: |
            sudo curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh
      - run:
          name: Start Docker Daemon
          command: sudo service docker start
      - run:
          name: Install dependencies
          command: |
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Build Docker image
          command: |
            docker build -t your_dockerhub_username/your_app_name .
      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push your_dockerhub_username/your_app_name

workflows:
  version: 2
  build_workflow:
    jobs:
      - build
