version: 2.1
jobs:
  build_and_push_image:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install Docker
          command: |
            curl -fsSL https://get.docker.com | sh
            sudo usermod -aG docker $USER
            sudo service docker start
      - run:
          name: Build Docker Image
          command: |
            docker build -t yakengne/python_api:1.0 .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push yakengne/python_api:1.0

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_and_push_image





