version: 2.1
jobs:
  build:
    docker:
      - image: python:3.9-slim

    working_directory: /app

    steps:
      - checkout
      - run:
          name: Install Docker
          command: |
            wget -O get-docker.sh https://get.docker.com
            sh get-docker.sh
            docker version
      - run:
          name: Install dependencies
          command: |
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Build Docker image
          command: |
            docker build -t your_dockerhub_username/your_app_name .
      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push your_dockerhub_username/your_app_name

workflows:
  version: 2
  build_workflow:
    jobs:
      - build

