version: 2.1
jobs:
  build:
    docker:
      - image: python:3.9.6  # Use the Python base image with Python 3.9.6
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            # Install any dependencies your Python application needs
            # For example, if you use pip, you can install requirements like this:
            pip install -r requirements.txt
            
      - run:
          name: Build and Test
          command: |
            # Add your build and test commands here
            # For example, if you are running tests with pytest:
            pytest tests/
          
      - run:
          name: Build Docker Image
          command: |
            # Build your Docker image here, assuming you have a Dockerfile in the root of your project
            docker build -t yakengne/python_api:1.0 .
            
      - run:
          name: Push Docker Image
          command: |
            # Push your Docker image to Docker Hub or any other container registry
            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
            docker push yakengne/python_api:1.0






