version: 2.1
jobs:
  build_and_push_image:
    docker:
      - image: circleci/python:3.8  # Choose an appropriate base image for your project

    steps:
      - checkout

      # Authenticate Docker using build-time secrets
      - run:
          name: Build and push Docker image
          command: |
            docker build -t yakengne/python_api:1.0 \
                         --build-arg DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME \
                         --build-arg DOCKERHUB_TOKEN=$DOCKERHUB_TOKEN \
                         .
            docker push yakengne/python_api:1.0

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_and_push_image




