version: 2.1
executors:
  docker-executor:  # Define a custom executor with Docker in Docker (DinD) service
    docker:
      - image: circleci/classic:latest
        environment:
          DOCKER_HOST: tcp://localhost:2375  # Set Docker host to access DinD service
    working_directory: ~/repo

jobs:
  build:
    executor: docker-executor  # Use the custom executor with DinD service
    steps:
      - checkout

      # Build the Docker image
      - run:
          name: Build Docker image
          command: |
            docker build -t yakengne/python_api:1.0 .

      # Log in to Docker Hub
      - run:
          name: Log in to Docker Hub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      # Push the Docker image to Docker Hub
      - run:
          name: Push Docker image to Docker Hub
          command: docker push yakengne/python_api:1.0

workflows:
  version: 2
  build_and_push:
    jobs:
      - build





