version: 2.1
executors:
  docker-executor:
    docker:
      - image: cimg/base:2020.01
        environment:
          # Set the DOCKER_CLI_ACI variable to disable BuildKit for Docker versions 20.10+
          DOCKER_CLI_ACI: "1"

jobs:
  build_and_push_image:
    executor: docker-executor
    steps:
      - checkout

      - setup_remote_docker:

      - run:
          name: Install Docker Compose
          command: |
            sudo apt-get update
            sudo apt-get install -y docker-compose

      - run:
          name: Build Docker image
          command: docker build -t yakengne/python_api:1.0 .

      - run:
          name: Log in to Docker Hub
          command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

      - run:
          name: Push Docker image to Docker Hub
          command: docker push yakengne/python_api:1.0

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_and_push_image



